name: FreePAN-IndexPages
version: 0.02
abstract: FreePAN IndexPages Plugin
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  FreePAN: 0
  SVK: 0.30
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
